Created triggers for Scale_prepare for Disable SELinux, Enable SSH root login, Enable SSH pubkey authentication, Disable SSH hostkey checking Default is true.
Rerunn of playbooks ends in that MSG: Incorrect type for fail_msg or msg, expected string and got <type 'list'>
"assert msg no longer accepts list #48547 Another option to configure this is to add stdout_callback = debug to your ansible.cfg" to get multiline
Change the msg under "update | Check if any running node needs to be updated" remove the split for "msg"

Added Current scale and available version in message banner

There was some error for installation of RPM:
Error: Invoking "yum" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name:
Change "install | Install GPFS RPMs"  "build | Install prereqs for building GPL module from source" to use name insted of with_item.